# Generated by Django 4.1.3 on 2022-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deal_price_dealitem_size_alter_dealitem_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dealitem',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='dealitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemquantity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemquantity',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemquantity',
            name='item_size',
        ),
        migrations.RemoveField(
            model_name='itemsize',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemsize',
            name='item',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='offeritem',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='DealItem',
        ),
        migrations.DeleteModel(
            name='ItemQuantity',
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferItem',
        ),
    ]
