# Generated by Django 4.1.3 on 2022-11-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_deal_items_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealitems', to='core.deal'),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
