# Generated by Django 4.1.3 on 2022-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.CharField(default='Not Specified', max_length=70),
        ),
    ]
